baseURL: https://tramfsl.netlify.com
languageCode: en-us
title: T.Ram Financial Services
theme: sangam

params: 
  subtitle: "Translating Opportunities to Growth"
  brand_color: "#237"
  contrast_color: "#295"
